spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shareit
    username: sharer
    password: Ilikeshare

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always

  logging:
    level:
      org:
        springframework:
          orm:
            jpa: INFO
            JpaTransactionManager: DEBUG
          transaction: INFO
          transaction.interceptor: TRACE

---
spring:
  config:
    activate:
      on-profile: ci,test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console